Accommodation search form
Skipper-Hospitality/organisms pull request #3
Opened 2022-03-29 10:36 UTC by nazmuldipu

Accommodation search form implemented

2022-03-29 11:55 UTC, xianmalik commented on index.html
> +    <a href="http://localhost:3000/accommodation-search-form/examples/accommodation-search-form.html">Accomation Seach Form</a>
Should this be localhost link? or relative link?

2022-03-29 11:55 UTC, xianmalik commented on accommodation-search-form/examples/accommodation-search-form.html
> +                console.log(picker.getCurrentEndDate());
Console logs present here

2022-03-29 12:45 UTC, azs06 requested changes

2022-03-29 12:45 UTC, azs06 commented on accommodation-search-form/accommodation-search-form.js
> +const renderGuest = () => {
I feel like this is something should be configureable, for example someone might allow more than 10 guests, some might have limitations of 5 at once.

2022-03-30 08:14 UTC, azs06 approved these changes

2022-03-30 08:38 UTC, merged

2022-03-30 08:38 UTC, azs06 commented
**Note: need to separate utility.js file**